### ISSUE TITLE
Error en codigo.

### ISSUE THREAD

**Issue by andresmoreta** [maestria-geotel-201902/unidad-2-asignacion-1-esda-operaciones-con-atributos-plots-andresmoreta#1]
Hola Maestro
No he podido seguir ejecutando la tarea, me da los errores que veras mas abajo
@geofis 

#Rótulos: valor de la variable
> proven17 %>%
+   dplyr::select(contains('Principales problemas de su barrio o comunidad: ¿Otro problema?')) %>%
+   gather(variable, valor, -geom) %>% 
+   ggplot() + aes(fill = valor) + geom_sf(lwd = 0.2) +
+   facet_wrap(~variable) + theme(text = element_text(size = 10)) +
+   scale_fill_gradientn(colours = RColorBrewer::brewer.pal(9, name = 'Reds'), trans = 'log10') +
+   geom_sf_text(aes(label=valor), check_overlap = T, size = 3)
Error in is_character(x) : object 'geom' not found
> 
> #Rótulos: nombres de las provincias
> proven17 %>%
+   dplyr::select(contains('Principales problemas de su barrio o comunidad: ¿Otro problema?'), TOPONIMIA) %>%
+   gather(variable, valor, -geom, -TOPONIMIA) %>% 
+   ggplot() + aes(fill = valor) + geom_sf(lwd = 0.2) +
+   facet_wrap(~variable) + theme(text = element_text(size = 10)) +
+   scale_fill_gradientn(colours = RColorBrewer::brewer.pal(9, name = 'Reds'), trans = 'log10') +
+   geom_sf_text(aes(label=TOPONIMIA), check_overlap = T, size = 3)
Error in is_character(x) : object 'geom' not found

**Comment by geofis** [comment]
@andresmoreta y al grupo completo @maestria-geotel-201902/estudiantes, si les aparece un error tal que el que te apareció a ti, o como el de Adalberto al ejecutar el `ggplot`, se debe a lo que explico a continuación.

Me remito a la línea 153 de tu `.Rmd`, donde tienes esto:

`proven17 <- en17 %>% inner_join(prov, by = 'ENLACE')`

Mira la clase de objeto que se genera:

```
class(proven17)
# [1] "data.frame"
```

Tu código le une a `en17` que es `data.frame` un objeto `sf`. Se preserva la clase del primer objeto; dicho de otra manera, el unido se "coacciona" a la clase del primero, que es `data.frame`. Esto hace que se pierda la clase `sf` del objeto `prov`. En tal sentido, si ejecutas esto verás que no tienes problemas:

```
proven17 <- prov %>% inner_join(en17, by = 'ENLACE')
class(proven17)
# [1] "sf"         "data.frame"
```

**Comment by geofis** [comment]
¿Podemos cerrar este *issue*?

**Comment by aleira** [comment]
Si.

**Comment by naui2003** [comment]
Si profe
