### ISSUE TITLE
Error encontrando libreria

### ISSUE THREAD

**Issue by andresmoreta** [maestria-geotel-201902/unidad-2-asignacion-1-esda-operaciones-con-atributos-plots-andresmoreta#2]
Hola @geofis 
El código me está dando error, no encuentra la librería kableExtra, he tratado de instalarla y no he podido

proven17 %>% st_drop_geometry() %>% +   dplyr::select(TOPONIMIA, contains('A qué cree usted que se debe la delincuencia en su barrio o comunidad: ¿Otra causa?')) %>%  +   gather(variable, valor, -TOPONIMIA) %>% group_by(TOPONIMIA) %>% +   mutate(pct=round(valor/sum(valor)*100,2)) %>% dplyr::select(-valor) %>% +   spread(variable, pct) %>% kableExtra::kable() 
Error in loadNamespace(name) : there is no package called ‘kableExtra’ > library(kableExtra) Error in 
library(kableExtra) : there is no package called ‘kableExtra’
 install.packages(kableExtra)
Error in install.packages : object 'kableExtra' not found

**Comment by geofis** [comment]
Interesante @andresmoreta 

Prueba de nuevo.

**Comment by geofis** [comment]
¿Podemos cerrar este *issue*?

**Comment by andresmoreta** [comment]
Buen día,

Si ese issue puede se cerrado
