### ISSUE TITLE
Encabezados fuera de margen

### ISSUE THREAD

**Issue by andresmoreta** [maestria-geotel-201902/unidad-2-asignacion-1-esda-operaciones-con-atributos-plots-andresmoreta#3]
Hola @geofis 
Al plotear los mapas, los textos de encabezados quedan fuera de los margenes y con parte del texto cortado, como por ejemplo:
proven17 %>%
  dplyr::select(contains('A qué cree usted que se debe la delincuencia en su barrio o comunidad: ¿Otra causa?')) %>%
  plot(breaks = 'jenks')
Me gustaria que me indique como mejorar esa parte

Saludos

**Comment by geofis** [comment]
@andresmoreta Prueba añadir `cex.main=0.5` a la función `plot`, por ejemplo:

```
proven17 %>%
dplyr::select(contains('A qué cree usted que se debe la delincuencia en su barrio o comunidad: ¿Otra causa?')) %>%
plot(breaks = 'jenks', cex.main = 0.5)
```


Juega con dicho valor (directamente proporcional al tamaño de letra del título).
